"""Add creator_profiles table

Revision ID: 3aa1c981a413
Revises: baf1112c55e2
Create Date: 2026-02-16 23:44:25.973140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa1c981a413'
down_revision = 'baf1112c55e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_url', sa.String(length=500), nullable=True),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('primary_genre', sa.String(length=50), nullable=True),
    sa.Column('content_style', sa.String(length=50), nullable=True),
    sa.Column('target_audience_age', sa.String(length=30), nullable=True),
    sa.Column('target_region', sa.String(length=10), nullable=True),
    sa.Column('creator_goal', sa.String(length=50), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('channel_description', sa.Text(), nullable=True),
    sa.Column('channel_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('channel_data_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creator_profiles')
    # ### end Alembic commands ###
