"""create videos table

Revision ID: 3bba4aa60f40
Revises: 
Create Date: 2025-11-16 09:19:56.281205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bba4aa60f40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_thumbnail', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('dislike_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('trending_country', sa.String(length=5), nullable=True),
    sa.Column('trending_date', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source_dataset', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_trending_country'), ['trending_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_trending_date'), ['trending_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_trending_date'))
        batch_op.drop_index(batch_op.f('ix_videos_trending_country'))
        batch_op.drop_index(batch_op.f('ix_videos_published_at'))
        batch_op.drop_index(batch_op.f('ix_videos_channel_id'))
        batch_op.drop_index(batch_op.f('ix_videos_category_id'))

    op.drop_table('videos')
    # ### end Alembic commands ###
