"""create_comments_table

Revision ID: 718c8585927b
Revises: fefd27d40834
Create Date: 2026-02-07 12:12:36.150542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718c8585927b'
down_revision = 'fefd27d40834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('author_display_name', sa.String(), nullable=True),
    sa.Column('text_display', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('emotion_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_video_id'))
        batch_op.drop_index(batch_op.f('ix_comments_published_at'))

    op.drop_table('comments')
    # ### end Alembic commands ###
