"""widen trending_country column

Revision ID: 93857942e797
Revises: 3bba4aa60f40
Create Date: 2025-11-16 09:53:38.236555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93857942e797'
down_revision = '3bba4aa60f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('trending_country',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('trending_country',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
