"""create_accuracy_logs_table

Revision ID: baf1112c55e2
Revises: 718c8585927b
Create Date: 2026-02-08 00:26:07.025773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf1112c55e2'
down_revision = '718c8585927b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accuracy_logs')
    # ### end Alembic commands ###
