"""add videos_clean table

Revision ID: d0677cbd58c2
Revises: 93857942e797
Create Date: 2025-11-16 11:21:18.220900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0677cbd58c2'
down_revision = '93857942e797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_clean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_clean', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags_text', sa.Text(), nullable=True),
    sa.Column('tags_clean', sa.Text(), nullable=True),
    sa.Column('description_clean', sa.Text(), nullable=True),
    sa.Column('trending_country_raw', sa.String(length=64), nullable=True),
    sa.Column('trending_country_code', sa.String(length=2), nullable=True),
    sa.Column('trending_date', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('dislike_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('source_dataset', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos_clean', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_clean_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_clean_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_clean_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_clean_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_clean_trending_country_code'), ['trending_country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_clean_trending_date'), ['trending_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_clean_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_clean', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_clean_video_id'))
        batch_op.drop_index(batch_op.f('ix_videos_clean_trending_date'))
        batch_op.drop_index(batch_op.f('ix_videos_clean_trending_country_code'))
        batch_op.drop_index(batch_op.f('ix_videos_clean_published_at'))
        batch_op.drop_index(batch_op.f('ix_videos_clean_genre'))
        batch_op.drop_index(batch_op.f('ix_videos_clean_channel_id'))
        batch_op.drop_index(batch_op.f('ix_videos_clean_category_id'))

    op.drop_table('videos_clean')
    # ### end Alembic commands ###
