"""add_comments_and_sentiment

Revision ID: fefd27d40834
Revises: df5dac3e2a2e
Create Date: 2026-02-07 12:00:54.038563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefd27d40834'
down_revision = 'df5dac3e2a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dominant_emotion', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('dominant_emotion')
        batch_op.drop_column('sentiment_score')

    # ### end Alembic commands ###
